repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: []
        pass_filenames: false
        args:
          - zscripts/application
          - zscripts/config.py
          - zscripts/configuration.py
          - zscripts/observability/logging.py
          - zscripts/observability/metrics.py
          - zscripts/observability/health.py
          - zscripts/observability/instrumentation.py
          - zscripts/extensions/scaffolding.py
          - zscripts/schemas
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [-q, -r, zscripts, examples/sample_project]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: npx --yes @commitlint/cli@19.3.0 --config commitlint.config.js --edit
        language: system
        stages: [commit-msg]
        pass_filenames: true
