import os

import pandas as pd

# Creating a DataFrame to represent the structure of the term set

data = {
    "Term Set Name": [
        "Natural World",
        "Natural World",
        "Natural World",
        "Natural World",
        "Natural World",
        "Cultural and Historical",
        "Cultural and Historical",
        "Cultural and Historical",
        "Cultural and Historical",
        "Geographical",
        "Geographical",
        "Geographical",
        "Geographical",
        "Scientific and Educational",
        "Scientific and Educational",
        "Scientific and Educational",
        "Scientific and Educational",
    ],
    "Term Set Description": [
        "Classification of natural elements",
        "Classification of natural elements",
        "Classification of natural elements",
        "Classification of natural elements",
        "Classification of natural elements",
        "Cultural and historical images",
        "Cultural and historical images",
        "Cultural and historical images",
        "Cultural and historical images",
        "Geographical locations and features",
        "Geographical locations and features",
        "Geographical locations and features",
        "Geographical locations and features",
        "Scientific and educational content",
        "Scientific and educational content",
        "Scientific and educational content",
        "Scientific and educational content",
    ],
    "Level 1 Term": [
        "Animals",
        "Plants",
        "Geology",
        "Microorganisms",
        "Ecosystems",
        "People",
        "Buildings and Structures",
        "Artifacts",
        "Historical Events",
        "Continents",
        "Countries",
        "Regions",
        "Landscapes",
        "Biological Processes",
        "Environmental Science",
        "Historical Research",
        "Educational Materials",
    ],
    "Level 2 Term": [
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    "Level 3 Term": [
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    "Level 4 Term": [
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    "Level 5 Term": [
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    "Level 6 Term": [
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    "Level 7 Term": [
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
}

df = pd.DataFrame(data)

# Directory where you want to save the file
folder_path = "documents"

# Create the folder if it doesn't exist
if not os.path.exists(folder_path):
    os.makedirs(folder_path)

# Full path for the file
excel_file_path = os.path.join(folder_path, "Structured_Term_Set_for_Biodiversity_Library.xlsx")

# Saving the DataFrame to an Excel file
df.to_excel(excel_file_path, index=False)
