# word_analysis.py
import collections
import json
import re
from typing import Any, Dict, List

import nltk
from nltk.corpus import stopwords

try:
    nltk.data.find("corpora/stopwords")
except LookupError:
    nltk.download("stopwords")

# these words will be added to the stop words
additional_stop_words = [
    "p",
    "br",
    "allow",
    "0",
    "style",
    "1",
    "us",
    "amazon",
    "iframe",
    "marketplace",
    "span",
    "div",
    "quot",
    "true",
    "amp",
    "com",
    "height",
    "width",
    "src",
    "font",
    "help",
    "adsystem",
    "also",
    "na",
    "linkid",
    "widgets",
    "ad",
    "advertising",
    "advertisingapi",
    "advertisingprogram",
    "api",
    "associate",
    "associates",
    "banner",
    "banners",
    "border",
    "bottom",
    "box",
    "3",
    "4",
    "5",
    "onejs",
    "marginwidth",
    "frameborder",
    "nobodyproduct",
    "h2",
    "2",
    "20",
    "source",
    "language",
    "forms",
    "operation",
    "q",
    "scrolling",
    "ws",
    "serviceversion",
    "20070822",
    "tracking_id",
    "ref",
    "region",
    "sandbox",
    "nobodyproduct",
    "120px",
    "240px",
    "marginheight",
    "getadhtml",
    "ad_type",
    "product_link",
    "placement",
    "a",
    "an",
    "the",
    "I",
    "you",
    "he",
    "she",
    "it",
    "we",
    "they",
    "me",
    "him",
    "her",
    "us",
    "them",
    "in",
    "on",
    "at",
    "by",
    "for",
    "with",
    "to",
    "from",
    "of",
    "about",
    "into",
    "onto",
    "upon",
    "through",
    "over",
    "under",
    "between",
    "among",
    "before",
    "after",
    "and",
    "or",
    "but",
    "nor",
    "so",
    "yet",
    "while",
    "because",
    "if",
    "unless",
    "although",
    "since",
    "when",
    "where",
    "until",
    "that",
    "good",
    "bad",
    "big",
    "small",
    "high",
    "low",
    "very",
    "really",
    "often",
    "sometimes",
    "usually",
    "never",
    "always",
    "now",
    "then",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "any",
    "both",
    "show_border",
    "show_price",
    "show_rating",
    "show_reviews",
    "show_title",
    "show_product_description",
    "show_featured_image",
    "link_opens_in_new_window",
    "scripts",
    "popups",
    "popup",
    "pop",
    "ups",
    "script",
    "scripting",
    "scripted",
    "scripter",
    "as_ss_li_til",
    "margin",
    "modals",
    "en_us",
    "nbsp",
    "asins",
    "ss",
    "color",
    "one",
    "new",
    "white",
    "black",
    "red",
    "blue",
    "green",
    "yellow",
    "orange",
    "purple",
    "pink",
    "conclusion",
    "align",
    "support",
    "li",
    "time",
    "like",
    "riddles",
    "emotional",
    "text",
    "pre",
    "origin",
    "role",
    "img",
    "alt",
    "may",
    "using",
    "many",
    "data",
    "type",
    "id",
    "class",
    "name",
    "value",
    "serif",
    "space",
    "social",
    "provide",
    "make",
    "skills",
    "week",
    "background",
    "clear",
    "even",
    "process",
    "1em",
    "h3",
    "well",
    "various",
    "h4",
    "h5",
    "h6",
    "left",
    "ol",
    "ai",
    "https",
    "understand",
    "article",
    "ul",
    "strong",
    "b",
    "beliefs",
    "section",
    "learning",
    "understanding",
    "funeral",
    "use",
    "create",
]

additional_stop_words = list(set(additional_stop_words))  # Remove duplicates


stop_words = set(stopwords.words("english"))  # Stop words from NLTK library

# add the additional stop words to the set of stop words
stop_words.update(additional_stop_words)


def load_posts() -> Dict[str, Any]:
    with open("all_posts.json", "r") as file:
        return json.load(file)


def get_words(posts: Dict[str, Any]) -> List[str]:
    words: List[str] = []
    for blog in posts.values():
        for post in blog["posts"]:
            words.extend(re.findall(r"\b\w+\b", post["content"].lower()))
    return words


def word_analysis():
    posts = load_posts()
    words = get_words(posts)
    words = [word for word in words if word not in stop_words]
    counter = collections.Counter(words)
    most_common_words = counter.most_common(50)  # You can change the number to get more or less words
    return most_common_words


if __name__ == "__main__":
    print(word_analysis())
