"""Generate a coverage summary from :mod:`trace` ``.cover`` files.

The standard `coverage` package is not available in the execution environment, so
we rely on Python's built-in :mod:`trace` module. This utility parses the
generated ``.cover`` files and emits a JSON summary that mirrors the per-file
coverage metrics typically produced by `coverage.py`.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


@dataclass
class CoverageStats:
    """Simple container for line coverage counts."""

    executed: int = 0
    missing: int = 0

    @property
    def total(self) -> int:
        """Return the total number of measured lines."""
        return self.executed + self.missing

    @property
    def coverage(self) -> float:
        """Return the coverage ratio as a float between 0 and 1."""
        if self.total == 0:
            return 1.0
        return self.executed / self.total


def parse_cover_file(path: Path) -> CoverageStats:
    """Parse a ``.cover`` file into :class:`CoverageStats`."""
    stats = CoverageStats()
    with path.open(encoding="utf-8") as handle:
        for raw_line in handle:
            if ":" not in raw_line:
                continue
            counter, _source = raw_line.split(":", 1)
            counter = counter.strip()
            if not counter or not counter.isdigit():
                continue
            if counter == "0":
                stats.missing += 1
            else:
                stats.executed += 1
    return stats


def summarise(directory: Path, prefix: str) -> dict[str, object]:
    """Build a coverage summary for modules that start with ``prefix``."""
    modules: list[dict[str, object]] = []
    totals = CoverageStats()

    for file in sorted(directory.glob("*.cover")):
        module_name = file.stem
        if not module_name.startswith(prefix):
            continue
        stats = parse_cover_file(file)
        totals.executed += stats.executed
        totals.missing += stats.missing
        modules.append(
            {
                "module": module_name,
                "path": module_name.replace(".", "/") + ".py",
                "executed_lines": stats.executed,
                "missing_lines": stats.missing,
                "total_lines": stats.total,
                "coverage": round(stats.coverage * 100, 2),
            }
        )

    return {
        "modules": modules,
        "totals": {
            "executed_lines": totals.executed,
            "missing_lines": totals.missing,
            "total_lines": totals.total,
            "coverage": round(totals.coverage * 100, 2),
        },
    }


def main() -> None:
    """Command-line entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "directory", type=Path, help="Directory containing .cover files generated by trace"
    )
    parser.add_argument(
        "--prefix",
        default="helpers.web_crawl",
        help="Only include modules whose dotted name starts with this prefix.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("artifacts/coverage/summary.json"),
        help="Output JSON file path.",
    )
    args = parser.parse_args()

    summary = summarise(args.directory, args.prefix)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(summary, indent=2) + "\n"
    args.output.write_text(payload, encoding="utf-8")


if __name__ == "__main__":
    main()
